defaultContentLanguage = "en"
languageCode = "en-us"
title = "Brieck's Pro"

relativeURLs = true

theme = "LoveIt"

[markup.goldmark.renderer]
    unsafe = true

[params]
    version="0.2.X"
    defaultTheme = "auto"
    gitRepo = "https://github.com/djbrieck/brieckspro"

[params.verification]
    bing = "7BD2A883C5B3DC557EA9AE85CD0D7C0A"

[menu]
    [[menu.main]]
      name = "About"
      url = "/about"
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    name = "Journal"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
#   [[menu.main]]
#     identifier = "tags"
#     pre = ""
#     post = ""
#     name = "Tags"
#     url = "/tags/"
#     title = ""
#     weight = 2
#   [[menu.main]]
#     identifier = "categories"
#     pre = ""
#     post = ""
#     name = "Categories"
#     url = "/categories/"
#     title = ""
#     weight = 3

#Author Config
[author]
name = "Daniel Brieck Jr"

[params.footer]
hugo = false
custom = "Brieck's Pro"
since = 2021
author = true
